name: Build VyOS Images
on:
  # Run every Sunday at 00:00
  schedule:
    - cron: '0 0 * * 0'
  # Run when manually triggered
  workflow_dispatch:
jobs:
  rolling-latest:
    name: Rolling Latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y squashfs-tools

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Fetch ISO
        run: curl -O https://s3.amazonaws.com/s3-us.vyos.io/rolling/current/vyos-rolling-latest.iso

      - name: Build
        run: ./build.sh vyos-rolling-latest.iso rolling-latest

      - name: Push
        run: docker push foltik/vyos:rolling-latest
